### ISSUE TITLE
Obsolete classes not referencing to new ones

### ISSUE THREAD

**Issue by thiagolunardi** [itext/itextsharp#11]
I found the one sample article about iTextSharp. I was using it to build a POC, and while I was coding I was being warned that "iTextSharp.text.html. simpleparse.HTMLWorker" is obsolete. OK then, but, what class should I use instead? This information should be given during development time.Please, advise at all obsolete classes and methods what new resource should we use instead.

**Comment by amedee** [comment]
For Professional Support, please see http://itextpdf.com/support
For Community Support, please ask your question on StackOverflow: http://stackoverflow.com/questions/tagged/itextsharp

**Comment by thiagolunardi** [comment]
Is was not a support, it was a request, or a suggestion, at least. But ok, it is free, so I do not deserve more attention. Tks for all.

**Comment by blagae** [comment]
I have run the numbers, and it seems like we add a message to the Obsolete annotation in about 60% of cases. Of course, these numbers could and should be improved.

In this particular case, a deprecation warning exists for the class documentation. However, the style of documentation is Javadoc, so that can, of course, also be improved because the .NET build process does not pick up on it.

**Comment by thiagolunardi** [comment]
Ok, maybe I can contribute to improve this coding time documentation. What do you think?

**Comment by amedee** [comment]
We always welcome a good pull request! :)
