### ISSUE TITLE
Arabic Language with visual studio 2015

### ISSUE THREAD

**Issue by mhand7** [itext/itextsharp#14]
I am using iTextsharp 5.5.9 with visual studio 2015. When I use it with visual studio 2013 to write arabic it works fine, but when I try to use the same code with visual studio 2015 it gives me questions marks. please refer to this questions on [stackoverflow](http://stackoverflow.com/questions/37262240/itextsharp-displaying-arabic)

I am not sure if I should post this issue here, but I could not find any place where to get help from. 

Thanks
Muhannad

**Comment by amedee** [comment]
Hello and thank you for opening an issue. For Community Support, we prefer to use StackOverflow. Keep in mind that this is on voluntary basis: an answer is not guaranteed and may not come from iText but from another user like yourself.
We use GitHub for bug reports and pull requests only.

If you are a customer with a support contract, you also have access to our JIRA, with direct communication with our developers and a guaranteed response.

Since you already asked a question on StackOverflow, I will close the issue here.
